### ISSUE TITLE
debug?

### ISSUE THREAD

**Issue by ghost** [neillturner/kitchen-puppet#218]
I'm trying to use the latest version of puppet_apply, but I'm getting this error after syncing the modules

Failed to complete #converge action: [undefined method `debug?' for #<Kitchen::Provisioner::Puppet::Librarian::LoggerUI:0x0000aaab12986be8>
Did you mean?  debug]

Any ideas?

**Comment by blodone** [comment]
+1 
Encountered the same error. Tried different versions but currently no clue where the error derives from

```
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [undefined method `debug?' for #<Kitchen::Provisioner::Puppet::Librarian::LoggerUI:0x00007f886002da10>
Did you mean?  debug] on default-ubuntu22-hosting-basesetup
D      ----------------------
D      ------Backtrace-------
D      /usr/local/rvm/gems/ruby-2.6.10/gems/test-kitchen-2.5.4/lib/kitchen/command.rb:183:in `report_errors'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/test-kitchen-2.5.4/lib/kitchen/command.rb:174:in `run_action'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/test-kitchen-2.5.4/lib/kitchen/command/action.rb:35:in `block in call'
D      /usr/local/rvm/rubies/ruby-2.6.10/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/test-kitchen-2.5.4/lib/kitchen/command/action.rb:33:in `call'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/test-kitchen-2.5.4/lib/kitchen/cli.rb:51:in `perform'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/test-kitchen-2.5.4/lib/kitchen/cli.rb:197:in `block (2 levels) in <class:CLI>'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/test-kitchen-2.5.4/bin/kitchen:11:in `block in <top (required)>'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/test-kitchen-2.5.4/lib/kitchen/errors.rb:170:in `with_friendly_errors'
D      /usr/local/rvm/gems/ruby-2.6.10/gems/test-kitchen-2.5.4/bin/kitchen:11:in `<top (required)>'
D      /usr/local/rvm/gems/ruby-2.6.10/bin/kitchen:23:in `load'
D      /usr/local/rvm/gems/ruby-2.6.10/bin/kitchen:23:in `<main>'
D      /usr/local/rvm/gems/ruby-2.6.10/bin/ruby_executable_hooks:22:in `eval'
D      /usr/local/rvm/gems/ruby-2.6.10/bin/ruby_executable_hooks:22:in `<main>'
D      ----End Backtrace-----
```

Edit: After Testing with multiple versions uninstalling various gems and reinstalling lead to no error anymore
currently with:
- ruby-2.5.9
- librarian-puppet 4.0.1
- kitchen-puppet 3.5.0
- test-kitchen 3.0.0
