### ISSUE TITLE
 Kitchen: Message: Failed to complete #converge action: [undefined local variable or method `modules_path' for 

### ISSUE THREAD

**Issue by i11** [neillturner/kitchen-puppet#59]
Seems like 0.0.29 release is broken:
```
E, [2015-07-24T12:50:03.996708 #25439] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2015-07-24T12:50:03.996737 #25439] ERROR -- Kitchen: Message: Failed to complete #converge action: [undefined local variable or method `modules_path' for #<Kitchen::Provisioner::PuppetApply:0x007f913e1752d8>]
E, [2015-07-24T12:50:03.996765 #25439] ERROR -- Kitchen: ---Nested Exception---
E, [2015-07-24T12:50:03.996839 #25439] ERROR -- Kitchen: Class: NameError
E, [2015-07-24T12:50:03.996889 #25439] ERROR -- Kitchen: Message: undefined local variable or method `modules_path' for #<Kitchen::Provisioner::PuppetApply:0x007f913e1752d8>
E, [2015-07-24T12:50:03.996921 #25439] ERROR -- Kitchen: ------Backtrace-------
E, [2015-07-24T12:50:03.996949 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/kitchen-puppet-0.0.29/lib/kitchen/provisioner/puppet_apply.rb:535:in `modules'
E, [2015-07-24T12:50:03.996977 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/kitchen-puppet-0.0.29/lib/kitchen/provisioner/puppet_apply.rb:814:in `prepare_modules'
E, [2015-07-24T12:50:03.997006 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/kitchen-puppet-0.0.29/lib/kitchen/provisioner/puppet_apply.rb:361:in `create_sandbox'
E, [2015-07-24T12:50:03.997032 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/provisioner/base.rb:61:in `call'
E, [2015-07-24T12:50:03.997061 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:366:in `block in converge_action'
E, [2015-07-24T12:50:03.997089 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `call'
E, [2015-07-24T12:50:03.997117 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-07-24T12:50:03.997144 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-07-24T12:50:03.997169 #25439] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-07-24T12:50:03.997196 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:452:in `action'
E, [2015-07-24T12:50:03.997224 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:362:in `converge_action'
E, [2015-07-24T12:50:03.997254 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-07-24T12:50:03.997330 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `each'
E, [2015-07-24T12:50:03.997363 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-07-24T12:50:03.997390 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:160:in `verify'
E, [2015-07-24T12:50:03.997416 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:189:in `block in test'
E, [2015-07-24T12:50:03.997442 #25439] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-07-24T12:50:03.997470 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:185:in `test'
E, [2015-07-24T12:50:03.997504 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/command.rb:176:in `public_send'
E, [2015-07-24T12:50:03.997531 #25439] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
```

**Comment by ytsarev** [comment]
I guess we should not merge pull requests ( https://github.com/neillturner/kitchen-puppet/pull/58 ) without rspec tests anymore

**Comment by grubernaut** [comment]
I completely missed that there weren't any tests. 

Sorry about this regression, I should have reviewed that better. I'll revert that PR, so master is clean and ask @neillturner if we can pull the 0.0.29 release. 

Apologies for any inconvenience this caused

**Comment by neillturner** [comment]
i didn't have time to test. just reviewed code. i will yank the gem.  -)

**Comment by grubernaut** [comment]
Thanks @neillturner. Could you also revert the PR? #58

Turns out I don't have revert perms :)

**Comment by neillturner** [comment]
reverted.

**Comment by i11** [comment]
thanks guys!

**Comment by neillturner** [comment]
close as codd reverted. not sure what i'd do about the contribution
